name: ldm
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.1.31=hbcca054_0
  - grpcio=1.62.2=py310h6a678d5_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - liblapack=3.9.0=8_openblas
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libprotobuf=4.25.3=he621ea3_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - markdown=3.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - packaging=24.2=pyhd8ed1ab_2
  - pip=25.0=py310h06a4308_0
  - protobuf=4.25.3=py310he36ed58_1
  - python=3.10.16=he870216_1
  - python_abi=3.10=2_cp310
  - re2=2022.04.01=h27087fc_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - tensorboard=2.19.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h52d8a92_1
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - addict==2.4.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - blinker==1.9.0
      - ccimport==0.4.4
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.1.8
      - cmake==3.31.6
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.1
      - cumm-cu120==0.4.11
      - cycler==0.12.1
      - cython==3.0.12
      - dash==3.0.0
      - decorator==5.2.1
      - easydict==1.13
      - efficientnet-pytorch==0.7.0
      - einops==0.8.1
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - fire==0.7.0
      - flask==3.0.3
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - h5py==3.13.0
      - huggingface-hub==0.29.3
      - icecream==2.1.4
      - idna==3.4
      - imageio==2.37.0
      - ipython==8.34.0
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - llvmlite==0.44.0
      - loguru==0.7.3
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - narwhals==1.31.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.3
      - numba==0.61.0
      - numpy==1.24.4
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - pandas==2.2.3
      - parso==0.8.4
      - pccm==0.4.16
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - plotly==6.0.1
      - portalocker==3.1.1
      - prompt-toolkit==3.0.50
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==2.13.6
      - pygments==2.19.1
      - pyparsing==3.2.1
      - pypcd==0.1.1
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-lzf==0.2.6
      - pytz==2025.1
      - pyyaml==6.0.2
      - referencing==0.36.2
      - requests==2.28.1
      - retrying==1.3.4
      - rpds-py==0.23.1
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - shapely==2.0.7
      - spconv-cu120==2.3.6
      - stack-data==0.6.3
      - stringcase==1.2.0
      - sympy==1.13.1
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - timm==1.0.15
      - torch==2.1.0+cu121
      - torch-tb-profiler==0.4.3
      - torchaudio==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==2.1.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==1.26.13
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
prefix: /home/ubuntu/anaconda3/envs/ldm
